### ISSUE TITLE
When a district, subdistrict or village is in activation or pre-activation there should be a visual indication

### ISSUE THREAD

**Issue by timlinux** [kartoza/fbf-project#100]
![image](https://user-images.githubusercontent.com/178003/70304109-15e75880-17f9-11ea-8814-9ca6ce7da556.png)

The districts should use iconography or colours (maybe using the drill in button 
![image](https://user-images.githubusercontent.com/178003/70304149-30213680-17f9-11ea-8f26-e33d025addad.png) colour would be good) to indicate the activation status for the district.

Also the list of districts/sub districts / villages should be ranked according to expected impact (@gubuntu please write a ticket to define how the logic should work for giving a single score) and then listed in descending order.

**Comment by lucernae** [comment]
@timlinux @NyakudyaA I think we also need Geoserver layer that can react with our selections.

For example, if we are on district summary view, we drew/zoom to the district borders using the activation color scheme.
If we are in the sub district summary view, we drew/zoom to the sub-district borders using the activation color scheme, etc.

**Comment by lucernae** [comment]
Just for confirmation, does our admin boundaries is coming from osm_admin?
CC @NyakudyaA .

**Comment by NyakudyaA** [comment]
> Just for confirmation, does our admin boundaries is coming from osm_admin?
> CC @NyakudyaA .

Our admin areas are not coming from OSM. I got them from https://data.humdata.org/dataset

**Comment by lucernae** [comment]
which table is in the database now?

**Comment by NyakudyaA** [comment]
> which table is in the database now?

![dist](https://user-images.githubusercontent.com/2510900/70314737-c6b51e00-1820-11ea-8d1a-c4b7fae8b5ce.png)

The yellow ones are in current use. the osm one is incomplete

**Comment by lucernae** [comment]
Ok! Thanks!

**Comment by lucernae** [comment]
@NyakudyaA , I need trigger_status in every summary table so I can know the status for each admin level.

**Comment by NyakudyaA** [comment]
> @NyakudyaA , I need trigger_status in every summary table so I can know the status for each admin level.

I have added them.

**Comment by timlinux** [comment]
> For example, if we are on district summary view, we drew/zoom to the district borders using the activation color scheme.
> If we are in the sub district summary view, we drew/zoom to the sub-district borders using the activation color scheme, etc.

This might be a case where just fetching the admin area as geojson might be more efficient and we can draw it as vector layer in openlayers.

**Comment by timlinux** [comment]
see also #137

**Comment by lucernae** [comment]
@timlinux fetching geojson and display it into the map with correct style is not easy to implement in this stack, because:
1. Postgrest is not able to return GeoJSON natively. If you want to return GeoJSON you need to convert it in postgis and return as GeoJSON in the table. Not trivial if there are future changes in the columns.
2. Consuming it in leaflet will involve writing GeoJSON layer handler. Compared with requesting WMS, providing style name, and give CQL filter, it would be way much easier for the front end guy.

**Comment by lucernae** [comment]
I'm done with the integration, just define the style guide first here to beautify it: #147 .
Then we can just change the CSS.
