### ISSUE TITLE
Cartography: Flood polygons should be semi-transparent

### ISSUE THREAD

**Issue by timlinux** [kartoza/fbf-project#104]
We need to be able to see the buildings behind the low flood class:

![image](https://user-images.githubusercontent.com/178003/70306530-f6532e80-17fe-11ea-8574-50435a51cee3.png)

**Comment by lucernae** [comment]
Hi @NyakudyaA , the layer is`kartoza:flood_forecast_layer`
I tried to use the one you make `flood_areas` but it won't filter, so I made another one.

**Comment by NyakudyaA** [comment]
Hi @lucernae, I can just delete the flood_areas, did you make it as a sql view or it's being derived in the DB

**Comment by NyakudyaA** [comment]
I have added transparency to the layer
![transparency](https://user-images.githubusercontent.com/2510900/70311263-fc0a3d80-1819-11ea-9db6-db55fde1c501.png)
