### ISSUE TITLE
We need the spreadsheet downloader

### ISSUE THREAD

**Issue by timlinux** [kartoza/fbf-project#109]
When browsing the flood events, 

![image](https://user-images.githubusercontent.com/178003/70310520-c0667800-1807-11ea-8a8c-8bf99c242d1e.png)

we should be able to download a spreadsheet:

![image](https://user-images.githubusercontent.com/178003/70310449-944af700-1807-11ea-8d3c-7b7c39ab2f9b.png)

The spreadsheet is a blob in the the flood_event table:

![image](https://user-images.githubusercontent.com/178003/70310552-d6743880-1807-11ea-9111-e85938f811a7.png)
When the download link is clicked use the PostgREST api to fetch it mime encoded as 

```
header('Content-Disposition: attachment; filename="name_of_excel_file.xls"');
```

so that when it downloads, it opens automatically in the user's desktop.

**Comment by lucernae** [comment]
I think it should have the MIME set too.

If the file is excel file.
`header('Content-Type: application/vnd.ms-excel');`
