### ISSUE TITLE
Name change

### ISSUE THREAD

**Issue by timlinux** [kartoza/fbf-project#118]
![image](https://user-images.githubusercontent.com/178003/70320329-54423f00-181c-11ea-8d8d-8ff6c0889269.png)
Change to Forecast Based Action

**Comment by meomancer** [comment]
this is svg 
http://maps.kartoza.com/Fbf/images/fbf-inasafe.svg

could you help me to update it @carina1000 ?

**Comment by carina1000** [comment]
Hi @meomancer I cant load that link. Please upload it - I've sent it via the slack channel. Then close this ticket! Thanks

**Comment by meomancer** [comment]
fixed by : https://github.com/kartoza/fbf-project/pull/143
need to wait @ann26 to deploy it
