### ISSUE TITLE
Map should show which buildings are flooded

### ISSUE THREAD

**Issue by timlinux** [kartoza/fbf-project#123]
When clicking a flood I dont get so see which buildings are flooded in a different colour any more.

**Comment by timlinux** [comment]
![image](https://user-images.githubusercontent.com/178003/70372757-2e2fa400-18db-11ea-8b5c-beb29d03cdf1.png)

I would like to follow this scheme for visualisation of flooded buildings:

Use a color gradient for flooded buildings based on their vulnerability. Green low vulnerability, red high vulnerability.
Have two flooded building layers for any flood event:
1) drawn with a red border are buildings that are in flood class 2 or higher
2) drawn with no border but using graduated colours for vulnerability are buildings that are in the flood footprint but in flood class 1 (low hazard)

The layer selector should let you toggle on or off buildings from the 2 groups as shown below.


![image](https://user-images.githubusercontent.com/178003/70372897-b5314c00-18dc-11ea-81d3-e6aeed8808ec.png)

**Comment by timlinux** [comment]
@gubuntu comment please

**Comment by timlinux** [comment]
See also #34 - we can close that when we close this

**Comment by lucernae** [comment]
Building's intersected materialized view needs to be populated first so we can have the layer by each flood event.
Ping me back/reassign when the layer is done 👍

**Comment by lucernae** [comment]
I made the corresponding PR here:
https://github.com/kartoza/fbf-project/pull/148

Layer spec:
```
Layer name: kartoza:exposed_buildings

Necessary fields for CQL filters:
 - depth_class: id of it's depth class of the building
 - dc_code: district code key from district table
 - sub_district_id: sub district code key from sub district table (sub_dc_code)
 - village_id: village code key from village table (village_code)

Fields for styling (in GeoServer styles)
 - vulnerability_score
 - depth_class
```

**Comment by NyakudyaA** [comment]
@lucernae I do not see the layer yet in GeoServer. Should I create it first. disregard my comment. Will create it first

**Comment by timlinux** [comment]
I added the needed view (see #134) and I have added the layer in GeoServer



![image](https://user-images.githubusercontent.com/178003/70374544-6c34c400-18eb-11ea-8914-1c949eeeec5e.png)


![image](https://user-images.githubusercontent.com/178003/70374492-b5384880-18ea-11ea-863d-05d1f1ceab69.png)

**Comment by NyakudyaA** [comment]
> I added the needed view (see #134) and I have added the layer in GeoServer
> 
> ![image](https://user-images.githubusercontent.com/178003/70374544-6c34c400-18eb-11ea-8914-1c949eeeec5e.png)
> 
> ![image](https://user-images.githubusercontent.com/178003/70374492-b5384880-18ea-11ea-863d-05d1f1ceab69.png)

I will modify the view to add the vulnerability score, should this remain slow we can turn the view into mview

**Comment by NyakudyaA** [comment]
I have added the style for the layer
![style-added](https://user-images.githubusercontent.com/2510900/70382122-1dc10d00-195f-11ea-8986-280b4b721fb1.png)

@timlinux what is the grading for vulnerability ?
 0 - 0.3 > low
0.4 - 0.6 > medium
0.7 - 1 > high

**Comment by lucernae** [comment]
@NyakudyaA The grading is on `depth_class` table itself with corresponding id.

**Comment by NyakudyaA** [comment]
> @NyakudyaA The grading is on `depth_class` table itself with the corresponding id.

The depth class I understand about it. meant the scale for the total_vulnerability

I have implemented this @lucernae 
![implemented](https://user-images.githubusercontent.com/2510900/70388643-2e07d500-19bd-11ea-9641-9648f5f45fb0.png)

**Comment by NyakudyaA** [comment]
This is now working as expected
