### ISSUE TITLE
Clicking on event returns nothing

### ISSUE THREAD

**Issue by timlinux** [kartoza/fbf-project#131]
<img width="418" alt="Screenshot 2019-12-07 at 07 52 04" src="https://user-images.githubusercontent.com/178003/70371089-89a36700-18c6-11ea-9abb-69838df868b4.png">

**Comment by anitanh** [comment]
hi @timlinux that's because the data boundary for that date does not exist

**Comment by meomancer** [comment]
this is because i was faking the 5 December, and the boundary does not exist

**Comment by lucernae** [comment]
Use 10th December for all the dummies we prepared (to drill down information).
Thanks @meomancer @ann26 for the dummies.
