### ISSUE TITLE
Spreadsheet download issue

### ISSUE THREAD

**Issue by timlinux** [kartoza/fbf-project#135]
Using Dec 10 event

![image](https://user-images.githubusercontent.com/178003/70372708-8f0aac80-18da-11ea-887a-829b8f689d98.png)

![image](https://user-images.githubusercontent.com/178003/70372715-9fbb2280-18da-11ea-8508-daf9585c84fd.png)

![image](https://user-images.githubusercontent.com/178003/70372719-af3a6b80-18da-11ea-8667-a6f920a80caf.png)

The spreadsheet looks good but all those messages are scary!

**Comment by meomancer** [comment]
should be fixed by this https://github.com/kartoza/fbf-project/pull/142

fixed by @dimasciput
