### ISSUE TITLE
Cartography for admin areas

### ISSUE THREAD

**Issue by timlinux** [kartoza/fbf-project#137]
When I click on an admin area in the dashboard and it drills down to it, the map must zoom to that area and the area boundary must be displayed on the map with a nice thick line.

**Comment by lucernae** [comment]
I've made PR for that in #146 to integrate the things.

CC @NyakudyaA  you need to define the style from geoserver for the following layers:
```
district_boundary
sub_district_boundary
village_boundary
```

CC @ann26 you need to follow up to group the layers in our map so that the boundaries will always be on top of all layers.

**Comment by anitanh** [comment]
done in https://github.com/kartoza/fbf-project/pull/146 and https://github.com/kartoza/fbf-project/pull/152
![Screenshot from 2019-12-08 12-43-50](https://user-images.githubusercontent.com/26101337/70384871-cd769900-19b8-11ea-9bcf-33d1810e6efa.png)
