### ISSUE TITLE
First dashboard tweaks

### ISSUE THREAD

**Issue by timlinux** [kartoza/fbf-project#160]
![image](https://user-images.githubusercontent.com/178003/70387526-11a87000-199e-11ea-887b-f13c85748717.png)

@ann26 to fix colours to match our style guide and use orange for pre-activation.

Can you also invert the order so it lists activation, pre-activation, floods

And use bigger chunkier text with good contrast

**Comment by meomancer** [comment]
Update based on : https://github.com/kartoza/fbf-project/issues/111#issuecomment-562541383
