### ISSUE TITLE
Deactivate osm_waterways and osm_roads

### ISSUE THREAD

**Issue by NyakudyaA** [kartoza/fbf-project#169]
# Problem

Since most of our analysis is based on buildings we should include the waterways and roads as part of the base map and remove the layers from the layer selector.

# Solution

I have already modified the base map to include those two layers in geoserver.

![fix](https://user-images.githubusercontent.com/2510900/70393424-43e3bd00-19f2-11ea-9c86-89bd18247438.png)

@ann26 Please let me know if it's a quick fix otherwise I can revert the base map and we can leave as is

**Comment by anitanh** [comment]
done in https://github.com/kartoza/fbf-project/pull/172
