### ISSUE TITLE
Road network density

### ISSUE THREAD

**Issue by timlinux** [kartoza/fbf-project#18]
Not used for all roads, exclude footpaths small tracks.

<img width="311" alt="image" src="https://user-images.githubusercontent.com/178003/67196267-63973580-f3f2-11e9-81e9-1d5333217b9c.png">

road_density | road_density_score
-- | --
0m | 1.0
0m – 1m | 0.8
1m – 2m | 0.5
more than 2m | 0.1
Unknown | 0.3

Methodology:

* take each building
* buffer it by a set distance
* calculate the distance of roads within that buffer
* assign the score for distance of roads to that building

**Comment by NyakudyaA** [comment]
Done already for the whole country, need to check the recoding only if all values are populated

**Comment by NyakudyaA** [comment]
This has now been implemented as trigger
