### ISSUE TITLE
Add vulnerability legend on the site

### ISSUE THREAD

**Issue by NyakudyaA** [kartoza/fbf-project#192]
# Problem

When the flooded buildings layer is visible on the map it should be added to the map

http://78.47.62.69/geoserver/wms?REQUEST=GetLegendGraphic&VERSION=1.0.0&FORMAT=image/png&WIDTH=20&HEIGHT=20&LAYER=kartoza:exposed_buildings

**Comment by NyakudyaA** [comment]
@ann26 Can we add an icon for the legend.
![legend-fba](https://user-images.githubusercontent.com/2510900/71094256-58bf0e00-21b3-11ea-8c68-752ef35e6723.png)


When the legend is closed it looks a bit vague not knowing what that is.

Maybe we could also have the legend initially fixed to where you have put it but make it float so that users can drag it around the map.

**Comment by anitanh** [comment]
hi @NyakudyaA @carina1000 can you suggest which icon to use?

**Comment by anitanh** [comment]
fix https://github.com/kartoza/fbf-project/pull/198
