### ISSUE TITLE
We need a legend for the flood layer

### ISSUE THREAD

**Issue by timlinux** [kartoza/fbf-project#208]
<img width="47" alt="image" src="https://user-images.githubusercontent.com/178003/71236864-ee63b600-22f7-11ea-94b7-608b458b452d.png">

It should reflect the classes and depth range for each class.

<img width="350" alt="image" src="https://user-images.githubusercontent.com/178003/71237037-63cf8680-22f8-11ea-9b9d-488e685747b9.png">

@NyakudyaA please hand over to @ann26 when you have it generating in WMS

**Comment by NyakudyaA** [comment]
@ann26 Please see the legend as specified here

http://78.47.62.69/geoserver/wms?REQUEST=GetLegendGraphic&VERSION=1.0.0&FORMAT=image/png&WIDTH=20&HEIGHT=20&LAYER=kartoza:flood_forecast_layer
