### ISSUE TITLE
Notes table

### ISSUE THREAD

**Issue by timlinux** [kartoza/fbf-project#211]
I would like to have a table for storing explanatory hazard_notes. The schema can be as simple as:

id (serial), notes (text), order (int), hazard_type(int)

and the hazard type table would be:

id (serial), name (text)
1, Flood forecast

After this report I am working on goes out I would like to refactor all the flood_ prefixed tables to be prefixed with hazard_ rather, and then each event should have a hazard_type_id. This will open the system to be used with other hazards e.g. cyclone in the future.

The hazard_notes table should be used to provide a set of notes in the report (dashboard and spreadsheet). In the spreadsheet it could maybe go in its own tab. In those notes we will emumerate all the caveats and constraints of the system. I can just edit the notes using my SQL client, no need for front end forms to manage it.

**Comment by NyakudyaA** [comment]
@timlinux I already created the notes table in the DB as `report_notes` 
![notes](https://user-images.githubusercontent.com/2510900/71245330-20d3da00-231d-11ea-925e-edcd8382e994.png)

Should we modify this or it's a seperate one ?

**Comment by timlinux** [comment]
Just modify this one thanks @NyakudyaA to include the hazard type and naming conventions

**Comment by NyakudyaA** [comment]
@timlinux I have created these tables but guess we should rename the column "order" to something because it conflicts with the reserved word in the DB.

**Comment by NyakudyaA** [comment]
This is done
