### ISSUE TITLE
Better display of buildings

### ISSUE THREAD

**Issue by timlinux** [kartoza/fbf-project#33]
<img width="338" alt="image" src="https://user-images.githubusercontent.com/178003/69333778-43f16800-0c51-11ea-817e-a9f249c7aefe.png">

We could make this much nicer as a sideways facinng bar chart. Talk to @carina1000 about establishing a nice colour scheme - colour gradiant from InaSAFE palette would be good:

<img width="446" alt="image" src="https://user-images.githubusercontent.com/178003/69334090-e14c9c00-0c51-11ea-8014-657723367aa4.png">

Should we rank them most to least? Might make more sense.

Also deal with the fact there may be big differences in bucket sizes so we dont want to end up with 

<img width="398" alt="image" src="https://user-images.githubusercontent.com/178003/69334206-2375dd80-0c52-11ea-8390-d0026d5b7928.png">

**Comment by timlinux** [comment]
Apply similar thinking to road counts and river counts too

**Comment by anitanh** [comment]
Dashboard is now using the new UI
