### ISSUE TITLE
Styling front end of the website

### ISSUE THREAD

**Issue by anitanh** [kartoza/fbf-project#49]
We can use this ticket for discussions about the style of the webs. Putting links, icons, mockups, etc.

**Comment by carina1000** [comment]
Hi @ann26 please see latest designs here https://www.figma.com/file/cBwVNP25R0emt5gC0oLrH4/FBF-Mocks?node-id=0%3A2

**Comment by carina1000** [comment]
Also latest version of the style guide
[FBF Style Guide_Draft 2.pdf](https://github.com/kartoza/fbf-project/files/3898249/FBF.Style.Guide_Draft.2.pdf)
