### ISSUE TITLE
zoom to extent of geojson feature

### ISSUE THREAD

**Issue by NyakudyaA** [kartoza/fbf-project#53]
When a user uploads a geojson we need to zoom to the extent of the feature.

# Solution

* I have already published the layer in geoserver `kartoza:flooded_area` with a red outline (we can change this)
* Use cql filter to show features for that layer using the id that you have assigned in the form ie
`&cql_filter=id=10`
* Write a function to zoom to the extent of the feature in leaflet

**Comment by lucernae** [comment]
@NyakudyaA I tried to use that layer, but somehow it always fails to filter.
I ended up creating another layer called `kartoza:flood_forecast_layer`

For the extent, I created postgres view called `flood_event_extent_v`
