### ISSUE TITLE
When selecting a flood it should zoom to the districts

### ISSUE THREAD

**Issue by timlinux** [kartoza/fbf-project#65]
And highlight the districts that are intersecting the flood using the district_ids 

Same for Sub-district and village

**Comment by NyakudyaA** [comment]
![flood_maps](https://user-images.githubusercontent.com/2510900/69986515-3cca3400-1546-11ea-979d-941a61858355.png)

Added three tables in GeoServer named `village,sub_district,district`.

This should be filtered by flood_event_id which is the id depicted in the above image

`cql_filter=flood_event_id=1`

@ann26 you can take over here

**Comment by timlinux** [comment]
Actually we will zoom to flood only and then show the boundaries
