### ISSUE TITLE
Fonts are wrong on site

### ISSUE THREAD

**Issue by timlinux** [kartoza/fbf-project#66]
![image](https://user-images.githubusercontent.com/178003/69938148-6ea2b280-14d4-11ea-8fa0-f0a80acfbd11.png)

**Comment by carina1000** [comment]
[FBF Style Guide_Draft 2.pdf](https://github.com/kartoza/fbf-project/files/3909963/FBF.Style.Guide_Draft.2.pdf)

See fonts to use on style guide

**Comment by anitanh** [comment]
fix in https://github.com/kartoza/fbf-project/pull/76
