### ISSUE TITLE
Flood browser behaviour

### ISSUE THREAD

**Issue by timlinux** [kartoza/fbf-project#67]
![image](https://user-images.githubusercontent.com/178003/69938239-ac9fd680-14d4-11ea-9e94-a345376ec322.png)

Circle icon to push the panel away to the bottom or pop it out the bottom

Carina to make pretty mockup

**Comment by timlinux** [comment]
Animation to come in from the bottom not side

**Comment by carina1000** [comment]
Please see design suggestions for this here: https://www.figma.com/file/mHl3t0f5xhwE0kj9J4izWi/FBF-Mocks-Version-2?node-id=0%3A1
