### ISSUE TITLE
Flood summary need to show in side panel

### ISSUE THREAD

**Issue by timlinux** [kartoza/fbf-project#69]
![image](https://user-images.githubusercontent.com/178003/69938416-3059c300-14d5-11ea-8f24-9e2bb7355608.png)

Show

* acquisition_date
* forecast_date
* source
* notes (nullable)
* link (nullable)

**Comment by carina1000** [comment]
What would the data of this "notes" data look like @timlinux @ann26 ?

**Comment by carina1000** [comment]
@timlinux @ann26 Let me know what you know what you think:
![Screenshot 2019-12-02 at 14 01 05](https://user-images.githubusercontent.com/35214829/69957887-52226c80-150c-11ea-9414-a695718e160d.png)

**Comment by anitanh** [comment]
@carina1000 a text like: `GloFAS`, I think that works

**Comment by carina1000** [comment]
Please see design suggestions for this here: https://www.figma.com/file/mHl3t0f5xhwE0kj9J4izWi/FBF-Mocks-Version-2?node-id=0%3A1
