### ISSUE TITLE
Tidy up for flood upload form

### ISSUE THREAD

**Issue by timlinux** [kartoza/fbf-project#70]
![image](https://user-images.githubusercontent.com/178003/69938641-ba099080-14d5-11ea-8073-cafaea174f0c.png)

Remove colons (:) after field labels

Souce - Source Typo

**Comment by timlinux** [comment]
![image](https://user-images.githubusercontent.com/178003/69938718-e58c7b00-14d5-11ea-9740-51136b06de3f.png)

Shoudl specify years after the return period size

**Comment by anitanh** [comment]
done in https://github.com/kartoza/fbf-project/pull/77
