### ISSUE TITLE
Flood uploader not working

### ISSUE THREAD

**Issue by timlinux** [kartoza/fbf-project#71]
![image](https://user-images.githubusercontent.com/178003/69938769-0b198480-14d6-11ea-8bcf-216f449e2581.png)

Just sits there when I press upload. I used the attached json

**Comment by timlinux** [comment]
[flood_classes.geojson.zip](https://github.com/kartoza/fbf-project/files/3909947/flood_classes.geojson.zip)

**Comment by lucernae** [comment]
@timlinux your flood contains Polygon feature while the database uses MultiPolygon geometry.

Try this one:
https://raw.githubusercontent.com/kartoza/fbf-project/develop/Datasets/Flood/flood_classes/flood_classes.geojson

**Comment by lucernae** [comment]
Perhaps we need to add these validations:

- The geojson file is a valid geojson
- The geojson file have `class` attribute with numeric value
- The geojson file each have MultiPolygon feature

**Comment by NyakudyaA** [comment]
@lucernae when you insert the geometry you just need to cast the geometry as multi
ie 
``` 
insert into foo (id, geom)
select id, st_multi(geom) as geom from foobar
```

**Comment by lucernae** [comment]
yeah but we are posting the feature thru PostgREST, I don't know if I was able to fix it using SQL.
