### ISSUE TITLE
Showing forecast information in calendar based on trigger status

### ISSUE THREAD

**Issue by timlinux** [kartoza/fbf-project#84]
I upload a flood:

![image](https://user-images.githubusercontent.com/178003/70118751-af2f3700-1660-11ea-847b-36d9ee6d3944.png)

I would expect to see a new circle in the calendar on the forecast date

![image](https://user-images.githubusercontent.com/178003/70118794-cbcb6f00-1660-11ea-99f0-9e9b6df73283.png)

Also maybe we should display a message indicating that the flood is being processed (or jump straight to the dashboard if the flood dashboard is ready). @NyakudyaA could put an extra field in flood_event called processing_state that shows in_progress or ready as valid options. In the first step of the post upload trigger we could set this to in_progress and the front end can regularly poll with a nice throbber showing we are still working. On the last step of the trigger, this field can be updated to done and the JS frontend could fetch that value and know it could go on to load the flood dashboard. Also the calendar would then update to show the trigger status.

@lucernae I think after our discussion yesterday, we should have a fourth state "flood event, no activation" which shows flood events that have e.g. been manually uploaded but that do not trigger activation.

![image](https://user-images.githubusercontent.com/178003/70119250-c0c50e80-1661-11ea-884d-f6f4708c4f77.png)

**Comment by meomancer** [comment]
need to update the historic logic
