### ISSUE TITLE
Landing experience

### ISSUE THREAD

**Issue by timlinux** [kartoza/fbf-project#91]
I would like to implement this story board. Catalina, Erin and @gubuntu I would love your feedback on the actual content.

@carina1000 make it beautiful!

@dimasciput can you work with @Samweli  to get it implemented tomorrow. Do it in a way that we can easily edit it if we get feedback with more content etc.

CC @ann26 FYI

I envisage that when the user opens the page they will not see the map but rather the landing experience. When clicking next we will have beautiful, smooth animations bringing the next image from the sequence into view. The image below describes this:

![image](https://user-images.githubusercontent.com/178003/70250245-8056b500-1775-11ea-88a3-7727013a7cc2.png)

Clicking the green flood browser icon will ease the map in over the story board, ready for action! Here is the full sequence of screens:

![storyboard](https://user-images.githubusercontent.com/178003/70250257-85b3ff80-1775-11ea-8c45-a172bb8921fc.png)

**Comment by meomancer** [comment]
it's done by @dimasciput
