### ISSUE TITLE
Flooded building count inconsistent with map

### ISSUE THREAD

**Issue by timlinux** [kartoza/fbf-project#95]
![Screenshot 2019-12-06 at 06 49 34](https://user-images.githubusercontent.com/178003/70302361-cbfc7380-17f4-11ea-87ef-e6fe7856bf83.png)

**Comment by NyakudyaA** [comment]
@timlinux this is still dummy data. I have just finished updating the id's for the focus area and will be updating the data shortly

**Comment by anitanh** [comment]
yes currently we are using dummy data from flood event id 15 because that is the one available. we can update it.
