### ISSUE TITLE
After selecting a date, please collapse the browser

### ISSUE THREAD

**Issue by timlinux** [kartoza/fbf-project#99]
![image](https://user-images.githubusercontent.com/178003/70304051-ed5f5e80-17f8-11ea-898a-5414ef36ac6d.png)

Or make the side bar div not scroll behind the picker

**Comment by lucernae** [comment]
Let's just collapse the browser if it's out of focus

**Comment by meomancer** [comment]
hi @timlinux 
i think this is solved
> Let's just collapse the browser if it's out of focus

it was annoying, because when we still selecting date and accidently out of box, it will close
so i remove this
but it will close when the date is selected
